name: WordPress Plugin Unit test

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  phpunit:
    name: WordPress ${{ matrix.wordpress }} * PHP v${{ matrix.php }} * ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ ubuntu-latest ]
        php: [ '7.1', '7.2', '7.3', '7.4' ]
        wordpress: [ latest, nightly ]
        multisite: [ 0, 1 ]

    env:
      PHP_VERSION: ${{ matrix.php }}
      WP_VERSION: ${{ matrix.wordpress }}
      WP_MULTISITE: ${{ matrix.multisite }}

    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP v${{ matrix.php }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: mbstring, intl, php-mysql

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14'

      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install gettext library
        run: sudo apt-get install gettext

      - name: Start MySQL
        # See https://github.blog/changelog/2020-02-21-github-actions-breaking-change-ubuntu-virtual-environments-will-no-longer-start-the-mysql-service-automatically/
        run: sudo /etc/init.d/mysql start

      - name: Install PHPUnit
        run: composer global require "phpunit/phpunit=4.8.*|5.4.*|5.7.*|6.*|7.*"

      - name: Install wp tests
        run: bash bin/install-wp-tests.sh wordpress_test root root localhost $WP_VERSION

      - name: Install Node.js package dependencies
        run: npm install

      - name: Build a plugin
        run: npm run build

      - name: Run PHPUnit - WordPress ${{ matrix.wordpress }}
        run: phpunit
