name: WordPress Plugin Unit test

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  phpunit:
    name: WordPress ${{ matrix.wordpress }} * PHP v${{ matrix.php }} * ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30

    strategy:
      fail-fast: false

      matrix:
        os: [ ubuntu-20.04 ]
        php: [ '7.1', '7.2', '7.3', '7.4', '8.0', '8.1', '8.2' ]
        wordpress: [ latest, nightly, '5.5' ]

        exclude:
          # PHP 8.0+ is not compatible with PHPUnit 7.x. on WordPress versions prior to 5.8 and should not be tested.
          - php: '8.0'
            wordpress: '5.5'
          - php: '8.1'
            wordpress: '5.5'
          - php: '8.2'
            wordpress: '5.5'

    env:
      PHP_VERSION: ${{ matrix.php }}
      WP_VERSION: ${{ matrix.wordpress }}

    services:
      database:
        image: mysql:5.7
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: root

    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP v${{ matrix.php }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: mbstring, intl, php-mysql

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Cache node modules
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install gettext library
        run: sudo apt-get install gettext

      - name: Install PHPUnit
        run: |
          # for PHP Compatibility - https://phpunit.de/supported-versions.html
          if [[ $PHP_VERSION == "7.0" ]] ; then
            composer global require "phpunit/phpunit=5.7.*|6.*"
          # for WP_VERSION < 4.6 due to PHP Fatal error: Class 'PHPUnit_Framework_TestCase' not found
          elif [[ ${PHP_VERSION:0:1} == "7" ]] && [[ "$WP_VERSION" < 4.6* ]] ; then
            composer global require "phpunit/phpunit=5.7.*"
          # for WP_VERSION < 5.0 due to Fatal error: Class PHPUnit_Util_Test may not inherit from final class (PHPUnit\Util\Test)
          elif [[ ${PHP_VERSION:0:1} == "7" ]] && [[ "$WP_VERSION" < 5.0* ]] ; then
            composer global require "phpunit/phpunit=5.7.*|6.*"
          elif [[ ${PHP_VERSION:0:1} == "8" ]] ; then
            composer global require "phpunit/phpunit=8.*"
          else
            composer global require "phpunit/phpunit=4.8.*|5.4.*|5.7.*|6.*|7.*"
          fi

      - name: Install PHPUnit Polyfills library
        run: composer global require "yoast/phpunit-polyfills=1.0.3"

      - name: Install wp tests
        run: bash bin/install-wp-tests.sh wordpress_test root root 0.0.0.0:3306 $WP_VERSION

      - name: Install Node.js package dependencies
        run: npm install

      - name: Build a plugin
        run: npm run build

      - name: Run PHPUnit - WordPress ${{ matrix.wordpress }}
        run: composer run phpunit
        continue-on-error: ${{ matrix.allow_failures == 'true' }}

      - name: Run Jest unit test - WordPress ${{ matrix.wordpress }}
        run: npm run test:jest
        if: ${{ matrix.php == '7.4' && matrix.wordpress == 'latest' }}
